default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

development:
  <<: *default
  host: localhost
  database: itcrowd_development

test:
  <<: *default
  host: localhost
  database: itcrowd_test

production:
  <<: *default
  database: itcrowd_production